version: '2'

services:
  rocketchat:
    image: rocketchat/rocket.chat:latest
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://rocketchat:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
#      - MAIL_URL=smtp://smtp.email
#      - HTTP_PROXY=http://proxy.domain.com
#      - HTTPS_PROXY=http://proxy.domain.com
    depends_on:
      - mongo
    ports:
      - 3000:3000
    # labels:
    #   - "traefik.backend=rocketchat"
    #   - "traefik.frontend.rule=Host: your.domain.tld"

  mongo:
    image: mongo:3.2
    restart: unless-stopped
    volumes:
     - ./data/db:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles --oplogSize 128 --replSet rs0
    # labels:
    #   - "traefik.enable=false"

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  # mongo-init-replica:
  #   image: mongo:3.2
  #   command: 'mongo mongo/rocketchat --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''localhost:27017'' } ]})"'
  #   depends_on:
  #     - mongo

  hubot-natural:
    image: diegodorgam/hubot-natural:latest
    restart: unless-stopped
    environment:
      - HUBOT_ADAPTER=rocketchat
      - HUBOT_OWNER=RocketChat
      - HUBOT_NAME='CatBot'
      - HUBOT_DESCRIPTION="Natural Language Processing with hubot"
      - HUBOT_HTTPD=false
      - ROCKETCHAT_URL=rocketchat:3000
      - ROCKETCHAT_USESSL=false
      - RESPOND_TO_DM=true
      - RESPOND_TO_LIVECHAT=true
      - LISTEN_ON_ALL_PUBLIC=false
      - ROCKETCHAT_USER=catbot
      - ROCKETCHAT_PASSWORD=123456
      - ROCKETCHAT_AUTH=password
      - HUBOT_LOG_LEVEL=debug
      - NATURAL_CORPUS=training_data/catbot-en.yml
      - NATURAL_LANG='en'
      # - LIVECHAT_DEPARTMENT_ID=kotKaj9JptWvwtJfJ
    volumes:
      - ./scripts:/home/hubotnat/bot/scripts
      - ./training_data:/home/hubotnat/bot/training_data
    depends_on:
      - rocketchat
    ports:
      - 8080:8080
